// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" }
import * as $$0 from "./islands/CreateMultisig.tsx"
import * as $$1 from "./islands/WalletConnect.tsx"
import * as $0 from "./routes/api/db_get.ts"
import * as $1 from "./routes/api/put_proxy.ts"
import * as $2 from "./routes/api/put_real.ts"
import * as $3 from "./routes/api/update_real.ts"
import * as $4 from "./routes/create-multisig.tsx"
import * as $5 from "./routes/create-transaction.tsx"
import * as $6 from "./routes/index.tsx"
import * as $7 from "./routes/transactions.tsx"

const manifest = {
  routes: {
    "./routes/api/db_get.ts": $0,
    "./routes/api/put_proxy.ts": $1,
    "./routes/api/put_real.ts": $2,
    "./routes/api/update_real.ts": $3,
    "./routes/create-multisig.tsx": $4,
    "./routes/create-transaction.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/transactions.tsx": $7,
  },
  islands: {
    "./islands/CreateMultisig.tsx": $$0,
    "./islands/WalletConnect.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
