name: Deploy
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - run: deno task star
      - run: deno run -A _tasks/deploy_import_map.ts
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: capi-multisig-app
          entrypoint: ./main.ts
