name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache
        run: deno task cache main.ts
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "capi-multisig-app"
          entrypoint: "./main.ts"
