name: Create Tokens Studio for Figma PR

# match the branch you put in your Tokens Studio for Figma sync credentials in the next step
on:
  push:
    branches:
      - figma-tokens

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "d-tokens" # match your default branch
          pr_title: "Figma Tokens Update"
          pr_body: "Design Tokens were updated in Figma. This PR contains the updated Tailwind config and CSS variables."
          github_token: ${{ secrets.GITHUB_TOKEN }}

  run_if: # only if base branch is "tokens-from-figma"
    if: ${{ github.head_ref == 'tokens-from-figma' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout to the head of this PR
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install Dependencies
        run: pnpm i style-dictionary --filter www

      - name: Build css using Style Dictionary
        run: |
          cd www
          node sd.config.cjs

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Donnie
          author_email: pelicansinberlin@gmail.com
          message: "chore: style-dictionary output"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "."
